version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: product-api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
